"""add_notifications_table

Revision ID: 76008186b149
Revises: a9d9ce41e20b
Create Date: 2025-11-07 23:20:38.446463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76008186b149'
down_revision = 'a9d9ce41e20b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sequelizemeta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))

    op.drop_table('sequelizemeta')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('login_method',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=True,
               existing_server_default=sa.text("'password'"))
        batch_op.alter_column('email_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_index(batch_op.f('idx_google_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_google_id'), ['google_id'], unique=False)
        batch_op.alter_column('email_verified',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('login_method',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               nullable=False,
               existing_server_default=sa.text("'password'"))

    op.create_table('sequelizemeta',
    sa.Column('name', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=255), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    mysql_collate='utf8mb3_unicode_ci',
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sequelizemeta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    # ### end Alembic commands ###
