"""add_google_oauth_fields_to_users

Revision ID: a9d9ce41e20b
Revises: 39fab74b68d7
Create Date: 2025-11-01 23:00:36.017925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9d9ce41e20b'
down_revision = '39fab74b68d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('login_method', sa.String(length=20), server_default='password', nullable=False))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_users_google_id', ['google_id'])
        batch_op.create_index('idx_google_id', ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_google_id')
        batch_op.drop_constraint('uq_users_google_id', type_='unique')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('login_method')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
